stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "building containers for integration environment"
    # remove all running containers on this server
    - if [[ -n $(docker ps -aq) ]]; then docker rm --force $(docker ps -aq); fi;
    # remove all existing volumes
    - docker volume prune --force
    # build services from scratch
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

test-api:
  stage: test
  script:
    - echo "Run api tests"

deploy-all:
  stage: deploy
  script:
    - echo "deploy to integration environment"

# deploy API integration
deploy-staging:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploy new build to staging server"
