# https://docs.docker.com/compose/yml/
# 
# docker-compose overrides for development.
# Note that this file is read automatically. 
#
# Example usage for development:
# docker-compose up
version: "3"
services:
  ifc-hive-docs:
    build:
      context: ./app/docs
      target: build
      args:
        NODE_ENV: development
    ports:
      - "8089:8089"
    volumes:
      - ./app/docs:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8089
    command: yarn run dev
