# https://docs.docker.com/compose/yml/
# This docker-compose file contains only generic entries which are to be use in
# all environments, i. e.
# 
# - development
# - testing
# - production
version: "3"
services:
  # Docs Service http://localhost:8089
  ifc-hive-docs:
    build:
      context: ./app/docs
  # API Service http://localhost:5000
  ifc-hive-api:
    build: ./app/api
  # Web-client http://localhost:8081
  ifc-hive-client:
    build: ./app/client
