# https://docs.docker.com/compose/yml/
# 
# docker-compose overrides for development.
# Note that this file is read automatically. 
#
# Example usage for development:
# docker-compose up
version: "3.7"
services:
  # Docs Service
  ifc-hive-docs:
    container_name: ifc-dev-docs
    build:
      context: ./app/docs
      target: build
      args:
        NODE_ENV: development
    ports:
      - "8089:8089"
    volumes:
      - ./app/docs:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8089
    command: yarn run dev

  # API Service
  ifc-hive-api:
    container_name: ifc-dev-api
    build:
      context: ./app/api
      args: 
        NODE_ENV: development
    volumes:
      - ./app/api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_TOKEN_SECRET=mysecret
      - API_TOKEN_MAX_AGE=86400
      - API_ROOT_EMAIL=daniel@karo.berlin
      - API_ROOT_PASSWORD=administrator
      - MONGO_URL=mongodb://mongo:27017/ifc-hive
    command: yarn run dev
    ports:
      - "8082:3000"

  # Registry Service
  ifc-hive-reg0:
    container_name: ifc-dev-reg0
    build:
      context: ./app/reg
      args:
        NODE_ENV: development
    volumes:
      - ./app/reg:/app
      #- /app/node_modules
    environment:
      - NODE_ENV=development
      - REG_HOST=ifc-dev-reg0
      - REG_TOKEN_SECRET=pacifico
      - REG_TOKEN_MAX_AGE=86400
      - REG_CLUSTER_CA_KEY=1
    command: yarn run dev
    ports:
      - "8083:3000"
  ifc-hive-reg1:
    container_name: ifc-dev-reg1
    build:
      context: ./app/reg
      args:
        NODE_ENV: development
    volumes:
      - ./app/reg:/app
      #- /app/node_modules
    environment:
      - NODE_ENV=development
      - REG_HOST=ifc-dev-reg1
      - REG_TOKEN_SECRET=customer1
      - REG_TOKEN_MAX_AGE=86400
    command: yarn run dev
    ports:
      - "8084:3000"
  ifc-hive-reg2:
    container_name: ifc-dev-reg2
    build:
      context: ./app/reg
      args:
        NODE_ENV: development
    volumes:
      - ./app/reg:/app
      #- /app/node_modules
    environment:
      - NODE_ENV=development
      - REG_HOST=ifc-dev-reg2
      - REG_TOKEN_SECRET=customer2
      - REG_TOKEN_MAX_AGE=86400
    command: yarn run dev
    ports:
      - "8085:3000"

  # Web-client
  ifc-hive-client:
    container_name: ifc-dev-client
    build:
      context: ./app/client
      target: build
      args:
        NODE_ENV: development
    volumes:
      - ./app/client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8081
      - VITE_API_BASE_URL=${API_BASE_URL:-http://localhost:8082}
      - VITE_APP_SOCKET_URL=${SOCKET_URL:-ws://localhost:8082/lab/websocket}
    ports:
      - "8081:8081"
    command: yarn run dev

  # MongoDB
  mongo:
    container_name: ifc-dev-mongo
