# https://docs.docker.com/compose/yml/
# 
# docker-compose overrides for development.
# Note that this file is read automatically. 
#
# Example usage for development:
# docker-compose up
version: "3"
services:
  # Docs Service
  ifc-hive-docs:
    container_name: ifc-dev-docs
    build:
      context: ./app/docs
      target: build
      args:
        NODE_ENV: development
    ports:
      - "8089:8089"
    volumes:
      - ./app/docs:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8089
    command: yarn run dev

  # API Service
  ifc-hive-api:
    container_name: ifc-dev-api
    build:
      context: ./app/api
      args: 
        NODE_ENV: development
    volumes:
      - ./app/api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn run dev
    ports:
      - "8082:3000"

  # Web-client
  ifc-hive-client:
    container_name: ifc-dev-client
    build:
      context: ./app/client
      target: build
      args:
        NODE_ENV: development
    volumes:
      - ./app/client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8081
      - VITE_API_BASE_URL=${API_BASE_URL:-http://localhost:8082}
    ports:
      - "8081:8081"
    command: yarn run dev
