# https://docs.docker.com/compose/yml/
# Use only production, note that you also need the docker-compose.yml file
#
# Example usage for production:
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: "3"
services:
  # Docs Service
  ifc-hive-docs:
    container_name: staging-docs
    build:
      context: ./app/docs
      args:
        - NODE_ENV=production
        - CI_COMMIT_SHA=${CI_COMMIT_SHA:-NO_COMMIT_SHA}
    ports:
      - "8029:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - CI_COMMIT_SHA=${CI_COMMIT_SHA:-NO_COMMIT_SHA}
  # API Service
  ifc-hive-api:
    container_name: staging-api
    build:
      context: ./app/api
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: yarn run start
    ports:
      - "8022:3000"
  # Web-client
  ifc-hive-client:
    container_name: staging-client
    build:
      context: ./app/client
      args:
        NODE_ENV: production
    ports:
      - "8021:80"
    environment:
      - NODE_ENV=production
      - PORT=80
