# https://docs.docker.com/compose/yml/
# This docker-compose file contains only generic entries which are to be use in
# all environments, i. e.
# 
# - development
# - testing
# - production
version: "3.7"
services:
  # Docs Service http://localhost:8089
  ifc-hive-docs:
    build:
      context: ./app/docs
  # API Service http://localhost:5000
  ifc-hive-api:
    build: ./app/api
    depends_on:
      - mongo
  # Registry Swarm Service http://localhost:8083
  ifc-hive-reg0:
    build: ./app/reg
    depends_on:
      - ifc-hive-api
  # Registry Swarm Service http://localhost::8084
  ifc-hive-reg1:
    build: ./app/reg
    depends_on:
      - ifc-hive-api
  # Registry Swarm Service http://localhost::8085
  ifc-hive-reg2:
    build: ./app/reg
    depends_on:
      - ifc-hive-api
  # Web-client http://localhost:8081
  ifc-hive-client:
    build: ./app/client
  mongo:
    image:  mongo:5.0.6
    restart: unless-stopped
    ports: 
      - "27017:27017"
    volumes:
      - ifc-dev-mongodb:/data/db
volumes:
  ifc-dev-mongodb:
