version: '3.7'
services:
  ifc-io:
    image: ifc-io:latest
    container_name: ifc-io
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=ifc-io-service.py
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    working_dir: /app
    command: "python3 -m flask run --host=0.0.0.0"
    # command: "python3 -m http.server 5000"

